// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hlmfvwtmxgcmknrzrqgp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhsbWZ2d3RteGdjbWtucnpycWdwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4MjI2MjUsImV4cCI6MjA2NTM5ODYyNX0.mUb71Lp1ec-1SvKPTjGCPRLwF7KqUx4jwTKr_xAyS4o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);